dmd:
  image: antonmeep/dmd
  script: ./test/run.sh && dub fetch covered && dub run covered -- -a test/.coverage/silly.lst
  coverage: '/Average: \d+\.\d+%/'

ldc:
  image: antonmeep/ldc
  script: ./test/run.sh
